# Site settings
title: 10GO@fucking_world:~#
description: H4ckSite
# baseurl: "/hello-fucking-world.github.io" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: H4ckSite
user_description: Antes pensaba que el deporte era mi pasion XD eso duro solo hasta el año pasado. Odio decir esto, pero bendita cuarentena. Gracias a ella, en gran parte, no solo descubri algo que me gustara sino que encontre algo que extrapola las leyes de este universo. Encontre mi pasion. Nunca nada cambio tanto mi vida como el haber encontrado mi pasion. Aun recuerdo cuando emepece a programar, fue algo sumamente interesante y bonito. Pero cuando llego el hacking todo eso se desbordo. Se transformo en mi mas hermosa historia de amor...
user_title: 10GO@fucking_world:~#
email: diego.osorio.dugo@gmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
